# Generated by Django 6.0.7 on 2026-09-12 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name'], 'verbose_name': 'Departamento/Servicio', 'verbose_name_plural': 'Departamentos/Servicios'},
        ),
        migrations.AddField(
            model_name='establishment',
            name='primary_color',
            field=models.CharField(choices=[('primary', 'Primary'), ('orange', 'Orange'), ('amber', 'Amber'), ('olive', 'Olive'), ('teal', 'Teal'), ('sky', 'Sky'), ('indigo', 'Indigo'), ('violet', 'Violet'), ('fuchsia', 'Fuchsia'), ('pink', 'Pink')], default='teal', max_length=20, verbose_name='Color principal'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='sidebar_color',
            field=models.CharField(choices=[('navy', 'Navy'), ('steel', 'Steel'), ('slate', 'Slate'), ('graphite', 'Graphite'), ('midnight', 'Midnight')], default='navy', max_length=20, verbose_name='Color del menú lateral'),
        ),
        migrations.AlterField(
            model_name='departmentleadership',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leaderships', to='organization.department', verbose_name='Departamento/Servicio'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leader_departament', to='organization.department', verbose_name='Departamento/Servicio'),
        ),
    ]
