# Generated by Django 6.0.7 on 2026-09-12 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_alter_department_options_establishment_primary_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='establishment',
            name='primary_color',
        ),
        migrations.RemoveField(
            model_name='establishment',
            name='sidebar_color',
        ),
    ]
